##SQL EXERCISE 2

##TASK 1
INSERT INTO `bonus` VALUES (6, 32000, '2021-11-2 09:00:00');
INSERT INTO `bonus` VALUES (6, 20000, '2022-11-2 09:00:00');
INSERT INTO `bonus` VALUES (5, 21000, '2021-11-2 09:00:00');
INSERT INTO `bonus` VALUES (9, 30000, '2021-11-2 09:00:00');
INSERT INTO `bonus` VALUES (8, 4500, '2022-11-2 09:00:00');

##TASK 2
SELECT
	SALARY
FROM
	WORKER
WHERE
	SALARY < (
		SELECT
			MAX(W.SALARY)
		FROM
			WORKER W
	)
ORDER BY
	SALARY DESC
LIMIT 1;


##TASK 3
SELECT
	FIRST_NAME,
LAST_NAME,
SALARY,
DEPARTMENT
FROM
	WORKER WHERE (SALARY,DEPARTMENT) IN (
SELECT MAX(SALARY),DEPARTMENT FROM WORKER GROUP BY DEPARTMENT
);


##TASK 4
SELECT
	FIRST_NAME,
LAST_NAME,
SALARY ,
DEPARTMENT
FROM
	WORKER WHERE (SALARY) IN (
SELECT SALARY FROM WORKER GROUP BY SALARY HAVING COUNT(WORKER_ID)>1
);


##TASK 5
SELECT
	W.FIRST_NAME,
	W.LAST_NAME,
	W.SALARY,
	W.DEPARTMENT,
	B.BONUS_AMOUNT
FROM
	WORKER W
LEFT JOIN BONUS B ON W.WORKER_ID = WORKER_REF_ID
AND SUBSTR(B.BONUS_DATE FROM 1 FOR 4) = '2021';



##TASK 6
DELETE FROM WORKER;
[SQL]DELETE FROM WORKER;
[Err] 1451 - Cannot delete or update a parent row: a foreign key constraint fails (`org`.`bonus`, CONSTRAINT `bonus_ibfk_1` FOREIGN KEY (`worker_ref_id`) REFERENCES `worker` (`WORKER_ID`))


##TASK 7
DROP TABLE WORKER;
[SQL]DROP TABLE WORKER;
[Err] 3730 - Cannot drop table 'worker' referenced by a foreign key constraint 'bonus_ibfk_1' on table 'bonus'.
